#! /bin/bash

all_tests=$(make --no-print-directory report_test_exes)

tests_to_run=""

if [ -e ".failed_tests" ]
then
	echo
	failed_tests=$(cat .failed_tests)
	new_tests=""
	for t in ${all_tests}
	do
		if [ "${t}" -nt ".failed_tests" ]
		then
			new_tests="${t}\n${new_tests}"
		fi
	done
	tests_to_run="${failed_tests}\n${new_tests}"
else
	tests_to_run="${all_tests}"
fi

rm -f .failed_tests
touch .failed_tests

tests_to_run=$(echo -e "${tests_to_run}" | sed -e '/^$/d' | sort -u)

if [ -z "${tests_to_run}" ]
then
	echo -e "\e[32mNo tests to run\e[0m"
	exit 0
fi

failed_tests_output=$(mktemp)
failed_tests=""
for t in ${tests_to_run}
do
	t_output=$(mktemp)
	if ! ./$t --gtest_color=yes > $t_output 2>&1
	then
		echo -e "[\e[31mFAILED\e[0m] $t"
		failed_tests="1"
		cat $t_output >> $failed_tests_output
		echo "${t}" >> .failed_tests
	else
		echo -e "[\e[32mPASSED\e[0m] $t"
	fi
	rm -f $t_output
done
if  [ "$failed_tests" = "1" ]
then
	echo
	echo
	cat $failed_tests_output
	rm -f $failed_tests_output
	echo
	echo -e "\e[31m***************************\e[0m"
	echo -e "\e[31m* SOME TESTS DID NOT PASS *\e[0m"
	echo -e "\e[31m***************************\e[0m"
	echo
	cat .failed_tests
	echo
	exit 1
fi
echo
echo -e "\e[32mALL TEST PASSED\e[0m"
rm -f $failed_tests_output
